#include "enums.h"

const char *roleStr[] = {
    "NP", "WCM", "VNM", "BCM", "MCM", "VSM", "BMS"
};

const char *stateStr[] = {
    "READY_FOR_LAUNCH", "DASH_CTL", "FAULT_STATE",
    "SAFE", "RUNNING", "EMERGENCY_BRAKE",
    "NORMAL_BRAKING", "FRONT_AXLE_BRAKING",
    "REAR_AXLE_BRAKING", "INFLATE",
    "WAITING_FOR_SAFE", "PUSH_PHASE",
    "COAST", "SPINDOWN"    
};

const char *faultStr[] = {
    "HEALTHY", 
    "GLOBAL_INITS_FAILED",
    "LOCAL_INIT_FAILED",
    "ILLEGAL_STATE",
    "ILLEGAL_ROLE",
    "UNINITIALIZED_HANDLER",
    "CAN_BUS_ERROR"    
};

const char *messageStr[] = {
    "INVALID",
    // OUT FROM POD MESSAGE TYPES
    "WCM_HB", "VNM_HB", "BCM_HB", "MCM_HB", "VSM_HB",
    "VNM_POS", "VNM_VEL", "VNM_ACC", "VNM_ATT", "VSM_TEMP1",
    "VSM_TEMP2", "VSM_EDATA", "BCM_BREAKSTATE", "BCM_BRAKESPEED1",
    "BCM_BRAKESPEED2", "MCM_KELLYSTATE", "MCM_CMDV",
    "MCM_HBSPEED1", "MCM_HBSPEED2", "VNM_STRIPLOST",
    //OUT FROM DASH MESSAGE TYPES
    "DASH_LAUNCH", "DASH_ESTOP", "DASH_RSTOP", "DASH_SAFE",
    "DASH_VNM_ENTERSTATE", "DASH_VNM_POSINDEXRESET",
    "DASH_VSM_ENTERSTATE", "DASH_BCM_ENTERSTATE",
    "DASH_BCM_AIRACTUATE", "DASH_BCM_BRAKEACTUATE",
    "DASH_BCM_ABS_STATE", "DASH_MCM_ENTERSTATE",
    "DASH_MCM_SPINWHEELS1", "DASH_MCM_SPINWHEELS2",
    "DASH_VSM_CONTRACTOR",
    // OUT FROM DASH MESSAGE TYPES      
    // NOT YET ADDED GLOBALLY (i.e. in spreadsheet)
    "TEST_MSG", "PING", "FAULT"    
};
